name: Deploy Server to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'EvaluationEngine/src/**'
      - 'EvaluationEngine/package*.json'
      - 'EvaluationEngine/tsconfig.json'
      - 'EvaluationEngine/.deployment'
      - 'EvaluationEngine/server.js'
      - 'EvaluationEngine/web.config'
      - '.github/workflows/deploy-server.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    
    - name: Install dependencies
      run: |
        cd EvaluationEngine
        npm ci
    
    - name: Build
      run: |
        cd EvaluationEngine
        npm run build
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'evaluation-engine-api' # Replace with your Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SERVER }}
        package: './EvaluationEngine'
