# Frontend React App Deployment to Azure Static Web Apps
# or Azure App Service

name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths: 
      - 'EvaluationEngine/client/**'

env:
  AZURE_WEBAPP_NAME: 'aitalentflow-frontend'
  NODE_VERSION: '18.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'npm install and build'
      run: |
        cd EvaluationEngine/client
        npm install
        npm run build

    - name: 'Deploy to Azure Static Web Apps'
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/EvaluationEngine/client"
        api_location: ""
        output_location: "build"
